# ═══════════════════════════════════════════════════════════════
#   拉玛西亚信息站 · 每日更新共用库
#
#   被 run_daily_update.ps1 与 run_daily_watchdog.ps1 共同引用。
#
#   设计要点（都是踩过的坑，改动前先读）：
#
#   1. 缓存类冲突 vs 源码类冲突必须分开处理。
#      判别是"双条件"：路径命中白名单 **且** 文件头含自动生成标识。
#      只看标识不行 —— scripts/update_*.ps1 自己的文件头也含该字符串。
#
#   2. 检测冲突残留在工作区，**不是**看索引状态。
#      2026-09-16 事故里残留文件在 git status 显示为 " M" 而非 "UU"，
#      任何基于 --diff-filter=U 的检测都抓不到，必须扫文件内容。
#
#   3. 消解一律用 origin/main，不用 --ours/--theirs。
#      rebase 期间这两个的语义与 merge 相反，是经典踩坑点。
#
#   4. status.json 必须算"自动生成类"。
#      它由本机与 Actions 双写，rebase 时必然冲突；
#      若归类为源码 → 每轮都判源码冲突 → 又一种自锁。
# ═══════════════════════════════════════════════════════════════

$script:LamAsiaRoot    = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$script:LamAsiaLogFile = Join-Path $script:LamAsiaRoot "scripts\local-daily-update.log"

function Set-LamAsiaLogFile([string]$path) {
  # 自测时把日志写到临时目录，不污染真日志
  $script:LamAsiaLogFile = $path
}

function Log-Line([string]$msg) {
  $line = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $msg"
  try { Add-Content -Path $script:LamAsiaLogFile -Value $line -Encoding UTF8 } catch { }
  Write-Host $line
}

# ── JSON 读写：无 BOM + LF，PS 5.1 的 Out-File -Encoding UTF8 会写 BOM，不能用 ──

function Write-JsonFile([string]$path, $obj) {
  $dir = Split-Path -Parent $path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  $json = $obj | ConvertTo-Json -Depth 6
  $json = $json -replace "`r`n", "`n"
  $enc  = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $json + "`n", $enc)
}

function Read-JsonFile([string]$path) {
  if (-not (Test-Path $path)) { return $null }
  try { return (Get-Content -Path $path -Raw -Encoding UTF8 | ConvertFrom-Json) }
  catch { return $null }   # 损坏时返回 $null，绝不抛异常
}

# ── 容错文本读取 ──
# Get-Content -Encoding UTF8 遇到非法字节序列会整行失败；配合 -ErrorAction SilentlyContinue
# 会把那些行静默丢掉（判别函数因此读不到标识）。这里按字节读再显式解码，非法字节原样保留。

function Read-TextFile([string]$path, [int]$MaxLines = 0) {
  if (-not (Test-Path $path)) { return @() }
  try {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $text  = (New-Object System.Text.UTF8Encoding($false)).GetString($bytes)
    $lines = $text -split "`r?`n"
    if ($MaxLines -gt 0 -and $lines.Count -gt $MaxLines) { return $lines[0..($MaxLines-1)] }
    return $lines
  } catch { return @() }
}

function Read-HeadLines([string]$path, [int]$n = 5) { return Read-TextFile $path $n }

# ── 自动生成文件判别（双条件，见文件头第 1 点） ──

function Test-AutoGeneratedPath([string]$rel) {
  $p = $rel -replace '\\', '/'
  if ($p -eq 'assets/data/status.json')  { return $true }   # 见文件头第 4 点
  if ($p -like 'assets/img/players/dqd/*') { return $true } # 二进制，无文件头可查
  if ($p -like 'scripts/dqd-videos-yt-shard.js') { return $true }
  if ($p -notlike 'assets/js/*.js') { return $false }       # 只认 assets/js 下的
  $name = Split-Path $p -Leaf
  return ($name -like '*cache*.js') -or ($name -eq 'fcb-youth-schedules.js')
}

function Test-AutoGeneratedFile([string]$root, [string]$rel) {
  if (-not (Test-AutoGeneratedPath $rel)) { return $false }
  $full = Join-Path $root $rel
  if (-not (Test-Path $full)) { return $true }   # 文件没了也按自动生成处理，反正重建
  # ★ 必须按字节读再显式用 UTF8Encoding 解码。
  #   用 Get-Content -Encoding UTF8 时，若文件里混入非法 UTF-8 字节序列（冲突标记、
  #   编码错乱的旧写入都会造成），PS 5.1 会解码失败；配上 -ErrorAction SilentlyContinue
  #   那些行会被**静默丢弃**，导致标识读不到、缓存被误判成手写源码。
  $head = Read-HeadLines $full 5
  return [bool]($head | Select-String -SimpleMatch '自动生成，请勿手动编辑' -Quiet)
}

# ── 冲突残留检测（见文件头第 2 点） ──

function Get-ConflictMarkerFiles([string]$root) {
  # 只扫已跟踪的文本文件，避免全树遍历
  $files = & git -C $root grep -l -E "^(<{7}|={7}|>{7})( |$)" -- 'assets' 'teams' '*.html' '*.css' '*.js' 'sw.js' 'scripts' 2>$null
  if (-not $files) { return @() }
  return @($files | Where-Object { $_ -and (Test-Path (Join-Path $root $_)) })
}

function Get-ConflictReport([string]$root) {
  $generated = @()
  $source    = @()
  foreach ($f in (Get-ConflictMarkerFiles $root)) {
    if (Test-AutoGeneratedFile $root $f) { $generated += $f } else { $source += $f }
  }
  return [pscustomobject]@{ Generated = $generated; Source = $source }
}

# ── git 包装：强制返回退出码，杜绝"调用方漏检" ──

function Invoke-Git {
  param([string]$Root, [string[]]$GitArgs)
  $out = & git -C $Root @GitArgs 2>&1
  return [pscustomobject]@{ Code = $LASTEXITCODE; Out = ($out -join "`n").Trim() }
}

function Assert-Git {
  param([string]$Desc, $Result, [System.Collections.ArrayList]$Failures)
  if ($Result.Code -ne 0) {
    Log-Line "  ✗ $Desc（退出码 $($Result.Code)）：$($Result.Out)"
    if ($Failures) { [void]$Failures.Add($Desc) }
    return $false
  }
  return $true
}

# ── 陈旧状态清理（"进程被杀"留下的硬残留） ──

function Clear-StaleGitState {
  param([string]$Root, [System.Collections.ArrayList]$Healed, [int]$LockMinutes = 30)
  $gitDir = Join-Path $Root '.git'

  foreach ($op in @(
      @{ Path = 'rebase-merge'; Cmd = 'rebase'; Arg = '--abort'; Code = 'stale_op_healed' },
      @{ Path = 'rebase-apply'; Cmd = 'rebase'; Arg = '--abort'; Code = 'stale_op_healed' },
      @{ Path = 'MERGE_HEAD';   Cmd = 'merge';  Arg = '--abort'; Code = 'stale_op_healed' },
      @{ Path = 'CHERRY_PICK_HEAD'; Cmd = 'cherry-pick'; Arg = '--abort'; Code = 'stale_op_healed' }
    )) {
    if (Test-Path (Join-Path $gitDir $op.Path)) {
      Log-Line "  ! 发现残留的 $($op.Cmd) 操作状态（$($op.Path)），正在中止"
      [void](Invoke-Git $Root @($op.Cmd, $op.Arg))
      if ($Healed) { [void]$Healed.Add($op.Code) }
    }
  }

  $lock = Join-Path $gitDir 'index.lock'
  if (Test-Path $lock) {
    $age = (Get-Date) - (Get-Item $lock).LastWriteTime
    if ($age.TotalMinutes -gt $LockMinutes) {
      Log-Line ("  ! 发现陈旧 index.lock（已存在 {0:N0} 分钟），删除" -f $age.TotalMinutes)
      Remove-Item $lock -Force -ErrorAction SilentlyContinue
      if ($Healed) { [void]$Healed.Add('stale_lock_healed') }
    } else {
      Log-Line ("  ! index.lock 仍新鲜（{0:N0} 分钟），可能有其它 git 进程在跑，本次不删" -f $age.TotalMinutes)
    }
  }
}

# ── 缓存产物新鲜度审计 ──
# 不能用文件 mtime：抓取脚本遵循"内容无变化则跳过写入"，mtime 天然可能是旧的

function Get-CacheUpdated {
  param([string]$Root, [string]$Rel)
  $full = Join-Path $Root $Rel
  if (-not (Test-Path $full)) { return $null }
  $head = Read-HeadLines $full 12
  foreach ($l in $head) {
    # 用 $Matches 而不是自己建的变量：$m/$args 之类是 PS 自动变量，会被意外覆盖
    if ($l -match '"updated"\s*:\s*"([^"]+)"') {
      $t = [datetime]::MinValue
      if ([datetime]::TryParse($Matches[1], [ref]$t)) { return $t }
      return $null
    }
  }
  return $null   # 该文件无 updated 字段（4 个 details + weekly-album）
}

# ── 告警：WinRT toast → WScript.Shell.Popup → alerts.log ──

function Test-AlertSuppressed {
  param([string]$Root, [string]$Key, [int]$Hours = 12)
  $st = Read-JsonFile (Join-Path $Root 'scripts\local-run-state.json')
  if (-not $st) { return $false }
  if (-not $st.lastAlertKey -or $st.lastAlertKey -ne $Key) { return $false }
  if (-not $st.lastAlertUtc) { return $false }
  $t = [datetime]::MinValue
  if (-not [datetime]::TryParse($st.lastAlertUtc, [ref]$t)) { return $false }
  return (((Get-Date).ToUniversalTime() - $t.ToUniversalTime()).TotalHours -lt $Hours)
}

function Send-LamAsiaAlert {
  param(
    [string]$Title,
    [string]$Body,
    [string]$Key = 'generic',
    [switch]$SkipSuppression,
    [switch]$ForcePopup
  )
  if (-not $SkipSuppression -and (Test-AlertSuppressed $script:LamAsiaRoot $Key)) {
    Log-Line "  (告警 '$Key' 12 小时内已发过，抑制重复弹窗；状态文件仍会更新)"
    return
  }

  $shown = $false
  if (-not $ForcePopup) {
    try {
      [void][Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType=WindowsRuntime]
      [void][Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType=WindowsRuntime]
      $template = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent(
                    [Windows.UI.Notifications.ToastTemplateType]::ToastText02)
      $nodes = $template.GetElementsByTagName('text')
      [void]$nodes.Item(0).AppendChild($template.CreateTextNode($Title))
      [void]$nodes.Item(1).AppendChild($template.CreateTextNode($Body))
      $toast = New-Object Windows.UI.Notifications.ToastNotification $template
      $appId = "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe"
      [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($appId).Show($toast)
      $shown = $true
      Log-Line "  → 已发送 Windows 通知：$Title"
    } catch {
      Log-Line "  (WinRT 通知不可用：$($_.Exception.Message)，回退弹窗)"
    }
  }

  if (-not $shown) {
    try {
      $shell = New-Object -ComObject WScript.Shell
      # 第二参数 15 = 15 秒自动消失；绝不用 0（会永久阻塞无人值守任务）
      [void]$shell.Popup($Body, 15, $Title, 48)
      Log-Line "  → 已弹出提示框：$Title"
    } catch {
      Log-Line "  (弹窗也不可用：$($_.Exception.Message))"
    }
  }

  try {
    Add-Content -Path (Join-Path $script:LamAsiaRoot 'scripts\alerts.log') `
      -Value "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  [$Key] $Title — $Body" -Encoding UTF8
  } catch { }

  # 记录去重状态（本地状态文件，不入库）
  $st = Read-JsonFile (Join-Path $script:LamAsiaRoot 'scripts\local-run-state.json')
  if (-not $st) { $st = New-Object psobject }
  $st | Add-Member -NotePropertyName lastAlertKey -NotePropertyValue $Key -Force
  $st | Add-Member -NotePropertyName lastAlertUtc -NotePropertyValue ((Get-Date).ToUniversalTime().ToString('o')) -Force
  Write-JsonFile (Join-Path $script:LamAsiaRoot 'scripts\local-run-state.json') $st
}

# ── 站点状态文件 ──
# 内容全 ASCII：PS 5.1 无 BOM 读中文会炸，中文由前端按枚举码映射

$script:LamAsiaStatusCodes = @{
  source_conflict = 'source_conflict'
  push_failed     = 'push_failed'
  add_failed      = 'add_failed'
  repo_error      = 'repo_error'
  run_incomplete  = 'run_incomplete'
  stale           = 'stale'
  fetch_failed    = 'fetch_failed'
}

function Publish-SiteStatus {
  param(
    [string]$Root,
    [string]$RunId,
    [string]$StartedUtc,
    [string]$FinishedUtc,
    [string]$LastSuccessUtc,
    [string]$Source = 'local',
    [string]$Status = 'ok',
    [int]$ExitCode = 0,
    [int]$ConsecutiveFailures = 0,
    [bool]$Blocked = $false,
    [string]$BlockedSinceUtc = $null,
    [string[]]$BlockedCodes = @(),
    [string[]]$FailedScripts = @(),
    [string[]]$StaleCaches = @(),
    [string[]]$Healed = @(),
    [int]$StaleHours = 36,
    [int]$HardStaleHours = 72
  )
  $obj = [ordered]@{
    schema              = 1
    runId               = $RunId
    runStartedUtc       = $StartedUtc
    runFinishedUtc      = $FinishedUtc
    lastSuccessUtc      = $LastSuccessUtc
    lastRunSource       = $Source
    lastRunStatus       = $Status
    exitCode            = $ExitCode
    consecutiveFailures = $ConsecutiveFailures
    blocked             = $Blocked
    # ConvertTo-Json 会把 $null 写成空串，这里统一成真正的 null，免得前端拿到 "" 还要额外判断
    blockedSinceUtc     = $(if ($BlockedSinceUtc) { $BlockedSinceUtc } else { $null })
    blockedCodes        = @($BlockedCodes)
    failedScripts       = @($FailedScripts)
    staleCaches         = @($StaleCaches)
    healed              = @($Healed)
    staleHours          = $StaleHours
    hardStaleHours      = $HardStaleHours
  }
  Write-JsonFile (Join-Path $Root 'assets\data\status.json') $obj
}
